// Code generated by tygo. DO NOT EDIT.
/**
 * Auto-generated from Go types
 * DO NOT EDIT MANUALLY
 *
 * To regenerate: npm run types:generate
 * Source: server/models/
 */

//////////
// source: models.go

/**
 * Coffee represents the coffee counter model
 */
export interface Coffee {
  id: number /* int */
  counter: number /* int */
  last_update: string
}
