// Code generated by tygo. DO NOT EDIT.
/**
 * Auto-generated from Go types
 * DO NOT EDIT MANUALLY
 * 
 * To regenerate: npm run types:generate
 * Source: server/models/
 */

//////////
// source: models.go

/**
 * Coffee represents the coffee counter model
 */
export interface Coffee {
  id: number /* int */;
  counter: number /* int */;
  last_update: string;
}
/**
 * ChatMessage represents a message in a chat conversation
 */
export interface ChatMessage {
  id: string;
  role: string;
  content: string;
  timestamp: string;
}
/**
 * ChatRequest represents the incoming chat request from the client
 */
export interface ChatRequest {
  message: string;
}
/**
 * ChatResponse represents a streaming chunk from the AI
 */
export interface ChatResponse {
  chunk: string;
}
